### PR TITLE
EN-2313 Component rating changes; Added tests

### PR DESCRIPTION
**Pull request by zonia3000**
Repeat tests after PR https://github.com/entando/entando-components/pull/514 has been merged

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Kerruba** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
