### PR TITLE
EN-2343 Changed interface name

### PR DESCRIPTION
**Pull request by zonia3000**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by rzsouza** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by zonia3000** [comment]
retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by rzsouza** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
